# -*- coding: utf-8 -*-
"""zeroShotClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0mUqWzta3fsN1vc6h6Y2H_VyG8V5tPa
"""

pip install transformers torch scikit-learn

from transformers import pipeline

# Initialize zero-shot-classification pipeline
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# Candidate priority labels with descriptions
labels = [
    "P0: Critical (production outage, urgent, security incident)",
    "P1: High (major feature broken, many users affected)",
    "P2: Medium (moderate issue, some impact)",
    "P3: Low (minor issue, feature request, cosmetic)"
]

# Example tickets
tickets = [
    "Our production server is down and users can't log in.",
    "Billing page shows wrong totals for some users.",
    "Can you add dark mode to the dashboard?",
    "Feature X is not working for multiple clients, needs fix ASAP."
]

# Classify each ticket
for ticket in tickets:
    result = classifier(ticket, candidate_labels=labels, multi_label=False)

    # Extract priority and confidence
    priority_label = result["labels"][0].split(":")[0]  # e.g., P0
    confidence = result["scores"][0]

    # Simple rationale
    rationale = f'Ticket classified as "{priority_label}" with confidence {confidence:.2f} based on ticket content.'

    # Output
    print("Ticket:", ticket)
    print("Priority:", priority_label)
    print("Confidence:", confidence)
    print("Rationale:", rationale)
    print("-" * 50)

result

